### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cloudfreexiao** [yika-aixi/SurvivalShooter-IcSkillSystem#1]
macos unity 2019.3 
![image](https://user-images.githubusercontent.com/14215026/67442900-34243b00-f635-11e9-9e19-8b86fcfe6a4b.png)

**Comment by yika-aixi** [comment]
@cloudfreexiao 分支切到`0.6Sync`，主分支我把修改的代码提交了部分:joy:

**Comment by cloudfreexiao** [comment]
还是有报错
![image](https://user-images.githubusercontent.com/14215026/67498893-c9b1e000-f6b2-11e9-84e8-01f30a127842.png)

**Comment by yika-aixi** [comment]
> 还是有报错
> ![图片](https://user-images.githubusercontent.com/14215026/67498893-c9b1e000-f6b2-11e9-84e8-01f30a127842.png)

IcSkillSystem分支是`0.6Struct`嘛?

**Comment by cloudfreexiao** [comment]
是的 难道我姿势不对？

**Comment by yika-aixi** [comment]
> 是的难道我姿势不对？

我知道了,我忘记提交了,我马上改下提交=-=稍等

**Comment by yika-aixi** [comment]
> 是的 难道我姿势不对？

推了,抱歉啊

**Comment by cloudfreexiao** [comment]
可以了
